### ISSUE TITLE
Error when parsing report with Sonar

### ISSUE THREAD

**Issue by ahmehri** [karma-runner/karma-junit-reporter#81]
When generating a report as the following:

```
<?xml version="1.0"?>
<testsuite name="Chrome 47.0.2526 (Linux 0.0.0)" package="" timestamp="2016-02-17T16:40:49" id="0" hostname="" tests="34" errors="0" failures="0" time="0.6">
  <properties>
    <property name="browser.fullName" value="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"/>
  </properties>
  <testcase name="test" time="0.049" classname="Chrome_47_0_2526_(Linux_0_0_0).Filter: stripExtension"/>
  <system-out>
    <![CDATA[
]]>
  </system-out>
  <system-err/>
</testsuite>
```

and after parsing it with Sonar, an error occurred:

> ERROR: Caused by: Unknown XML node, expected "unitTest" but got "testsuite"

**Comment by jpaulin** [comment]
This seems to basically say that Karma JUnit reporter has been configured to use a naming convention true to test code (source), whereas Sonar expects something different. 

The karma-junit-reporter produces lines to the test report so that it makes a <testsuite> tag for a test class (usually that's a physical single file), and within the test suites there are <testcase> tags, one for each named test spec. 

Can you configure both ends, Karma and the Sonar? A question that might help check out the options available.

**Comment by ahmehri** [comment]
@jpaulin Sonar uses a specific XSD schema for the report. A sample of a compliant file can be found [here](http://docs.sonarqube.org/display/PLUG/Generic+Test+Coverage) in the section _Unit Tests Execution Results Report Format_. Therefore I don't think that there is a possible configuration at Sonar side.

**Comment by jehon** [comment]
Coming accross the same problem.
I see this bug too about the same problem: #78
